#
#    S P Y C
#      a simple php yaml class
#
# authors: [vlad andersen (vlad.andersen@gmail.com), chris wanstrath (chris@ozmm.org)]
# websites: [http://www.yaml.org, http://spyc.sourceforge.net/]
# license: [MIT License, http://www.opensource.org/licenses/mit-license.php]
# copyright: (c) 2005-2006 Chris Wanstrath, 2006-2011 Vlad Andersen
#
# spyc.yml - A file containing the YAML that Spyc understands.

---

# Mappings - with proper types

database:
  host: localhost
  driver: pdo_mysql
  user: root
  password: 
  dbname: lightcdn
allowed servers: 
   - abc.com
   - 123.com
   - etc.com
   - img3.cache.netease.com
   - purelogics.net
   - localhost
   - www.pragmasoftwares.com
   - www.google.com
   - www.bing.com
   - a248.e.akamai.net
   - samplepdf.com
   - g-ecx.images-amazon.com
   - www.youtube.com
setting:
  max space : 20
  
