#
#    S P Y C
#      a simple php yaml class
#
# authors: [vlad andersen (vlad.andersen@gmail.com), chris wanstrath (chris@ozmm.org)]
# websites: [http://www.yaml.org, http://spyc.sourceforge.net/]
# license: [MIT License, http://www.opensource.org/licenses/mit-license.php]
# copyright: (c) 2005-2006 Chris Wanstrath, 2006-2011 Vlad Andersen
#
# spyc.yml - A file containing the YAML that Spyc understands.

---

# Mappings - with proper types

database:
  host: localhost
  driver: pdo_mysql
  user: root
  password: 
  dbname: lightcdn
allowed servers: 
   - abcd.com
setting:
  max space : 30
  
